### ISSUE TITLE
Call don't going via Interaction client "Web Edition" only invoking in Interaction client "Windows App"

### ISSUE THREAD

**Issue by amitsonihp** [GenesysPureConnect/ChromeClickToDialExtension#2]
Hi Team,
             I am try to do following task..
The click to call plugins will turn phone numbers on web pages into clickable links. When clicking the links, the callto: uri is called for external applications like the desktop Interaction Client to handle. It can also use the web client to dial numbers if it is running in another tab.

for that i did following things:
1. I installed "Interaction Center Click-To-Dial" plugin in browser.
2. I did download the "ChromeClickToDialExtension-master" project from this url:https://github.com/InteractiveIntelligence/ChromeClickToDialExtension and i am running testpage.html 

Issue:
Only call is going via Interaction client "windows application" not via "Web Edition" when we keeping a link in "testpage.html"
By default any link is not coming in "testpage.html" where as if i running by this url:https://raw.githubusercontent.com/InteractiveIntelligence/ChromeClickToDialExtension/master/testpage.html  call is going fine via both client win as well as web.

So,I request you to please help me on the same as soon as possible.I will be  thankful for this kind help.

Please contact me on that.
Amit Kumar
Mob:+91-7411108325
Email :amitsonihp@gmail.com

**Comment by KevinGlinski** [comment]
If you are running testpage.html locally and the url for it in chrome is file://...testpage.html then chrome won't replace the numbers for it.  It will only work for http/https

**Comment by amitsonihp** [comment]
Hi @KevinGlinski ,
                            Thanks a lot specially for your valuable response on the same..."Thanks Kevin!"
